### ISSUE TITLE
The ApiReference class should not contain assertions.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/wcms-qa-testing-framework#33]
The ApiReference class contains a verifyApiReferenceLink() method. This method should be refactored to:

* Change its name to reflect what its intended purpose (e.g. ClickApiReferenceLink)
* Return a page object containing the page which is returned by clicking the link.
* Change the return type from `void` to a general page object type. (The calling method is responsible for determining whether the correct page was returned.)

**Comment by SupriyaSaxena0605** [comment]
This is fixed and there are no more Assertions in ApiReference class
