### ISSUE TITLE
qa-auto1 branch - test runner fails on startup with a 'null value' error.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/wcms-qa-testing-framework#49]
1. Switch to the qa-auto1 branch
2. Command line, change to the project root folder
3. Execute the command `mvn test`

Execution terminates with the message:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test (default-test) on project nci: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test failed: testSuiteXmlFiles0 has null value -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Comment by blairlearn** [comment]
This appears to have  been caused by commit 445d3a6.  In `pom.xml`, the list of specific file named in the `suiteXmlFiles/file` element has been replaced by a commented-out file and a new `<suiteXmlFile>${suiteXmlFile}</suiteXmlFile>` entry.

Undoing that specific change allows the tests to run.

**Comment by SupriyaSaxena0605** [comment]
Giving the testng-CTS.xml as parameter while executing the tests using the command mvn clean test -Dsurefire.suiteXmlFiles=resources/testng-CTS.xml
This issue is fixed and the Test Suite is running without any error. I am working on one issue that the maven test is not reading test data from excel file.

**Comment by blairlearn** [comment]
Confirmed. With the addition of 3d9239a, running `mvn test` with no other parameters now behaves as expected.
